#!/usr/bin/env python3
"""
Build the Hebrew MAIN and BONUS word lists for the daily word-grid game.

Run once (on a machine with the `wordfreq` package); copy the resulting
data/main.txt and data/bonus.txt into the air-gapped network. The game core
itself needs only those two files and the standard library.

Sources
  sources/all_no_fatverb.txt   Hspell 1.4: every valid inflected form, no prefixes
  sources/{nouns,adjectives,verbs_no_fatverb,gerunds,prepositions}.txt
                               Hspell forms by part of speech. Hspell forms outside
                               these lists are mostly proper names, so they are dropped
                               unless listed in data/function_words.txt
  data/function_words.txt      untagged-but-real words (עכשיו, אתמול, שלושה...)
  data/extra_spellings.txt     2017 Academy spellings Hspell lacks (חוכמה, תיאטרון...)
  data/slang.txt               colloquial words -> always BONUS
  data/blocklist.txt           never valid; the generator also keeps them off boards
  data/blocked_lemmas.txt      block EVERY form of these words (matched on Hspell's lemma);
                               all blocked forms are written to data/blocked_forms.txt
  data/exclude.txt             proper nouns Hspell tags as nouns (ישראל, לונדון...)
  data/morph.tsv               grammar of each form, from Hspell's morphology
                               (made by analyze_hspell.py): plain / bound / infinitive / name
  wordfreq (he)                frequency (Zipf scale: 3 = once per million words)

Rules
  MAIN  = dictionary headwords and infinitives (נעול, פגיע, פתיר, לתרום) with Zipf >= --main-zipf
          (default 2.5: real words people know, not only the most frequent ones)
          + ordinary inflections (ספרים, מורכבת, למדו) with Zipf >= --inflected-zipf (default 3.3)
  BONUS = bound forms: construct (סמיכות: גינת, פגיעת) and possessive suffixes
          (כינוי חבור: לועי, ספריו), Zipf >= --bonus-zipf (default 1.5)
          + plain forms that are rarer than MAIN (Zipf --bonus-zipf .. --main-zipf)
          + slang with Zipf >= --slang-zipf (default 1.0; proves it's in real use)
  Only words of --min-len+ letters made of the 27 Hebrew letters are kept.

Word lists derived from Hspell are AGPL-3.0 (see sources/COPYING).
"""

from __future__ import annotations

import argparse
from pathlib import Path

from wordfreq import zipf_frequency

HERE = Path(__file__).parent
SRC, DATA = HERE / "sources", HERE / "data"
HEBREW = set("אבגדהוזחטיכלמנסעפצקרשתךםןףץ")
FINALS = set("ךםןףץ")


def read_list(path: Path) -> set[str]:
    out = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        w = line.strip()
        if w and not w.startswith("#"):
            out.add(w)
    return out


def well_formed(w: str, min_len: int) -> bool:
    """Hebrew letters only; final forms allowed only at the end."""
    return (len(w) >= min_len and set(w) <= HEBREW
            and not any(c in FINALS for c in w[:-1]))


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--min-len", type=int, default=4)
    p.add_argument("--main-zipf", type=float, default=2.5)
    p.add_argument("--inflected-zipf", type=float, default=3.3)
    p.add_argument("--bonus-zipf", type=float, default=1.5)
    p.add_argument("--slang-zipf", type=float, default=1.0)
    a = p.parse_args()

    hspell = read_list(SRC / "all_no_fatverb.txt")
    tagged = set().union(*(read_list(SRC / f) for f in (
        "nouns.txt", "adjectives.txt", "verbs_no_fatverb.txt",
        "gerunds.txt", "prepositions.txt")))
    function_words = read_list(DATA / "function_words.txt")
    extra = read_list(DATA / "extra_spellings.txt")
    slang = read_list(DATA / "slang.txt")
    blocked = read_list(DATA / "blocklist.txt")
    excluded = read_list(DATA / "exclude.txt")
    rows = [line.split("\t") for line in
            (DATA / "morph.tsv").read_text(encoding="utf-8").splitlines() if line]
    morph = {r[0]: r[1] for r in rows}
    lemmas = {r[0]: set(r[2].split(",")) if len(r) > 2 and r[2] else set() for r in rows}

    # block every form of a blocked word
    bad_lemmas = read_list(DATA / "blocked_lemmas.txt")
    for w in blocked:
        # only through a lemma that is itself blocked: פרחה (slang) must not
        # take every form of פרח (flower) with it, nor חרמן take חרם
        bad_lemmas |= lemmas.get(w, set()) & (blocked | {w})
    blocked_forms = {w for w, ls in lemmas.items() if ls & bad_lemmas} | blocked
    (DATA / "blocked_forms.txt").write_text(
        "# generated by build_wordlists.py from blocklist.txt + blocked_lemmas.txt\n"
        + "\n".join(sorted(blocked_forms)) + "\n", encoding="utf-8")
    blocked = blocked_forms
    infinitives = {w for w, k in morph.items() if k == "infinitive"}
    names = {w for w, k in morph.items() if k == "name"}

    valid = (hspell & tagged) | function_words | extra | infinitives
    valid = {w for w in valid if well_formed(w, a.min_len)} - blocked - slang - excluded - names

    main_words, bonus_words = {}, {}
    for w in valid:
        z = zipf_frequency(w, "he")
        kind = morph.get(w, "base")             # hand-listed words count as headwords
        if (kind in ("base", "infinitive") and z >= a.main_zipf) or \
           (kind == "plain" and z >= a.inflected_zipf):
            main_words[w] = z
        elif z >= a.bonus_zipf:
            bonus_words[w] = z
    slang_kept = 0
    for w in slang - blocked:
        z = zipf_frequency(w, "he")
        if well_formed(w, a.min_len) and z >= a.slang_zipf:
            bonus_words[w] = z
            slang_kept += 1

    for name, words in (("main.txt", main_words), ("bonus.txt", bonus_words)):
        lines = [f"{w}\t{z:.2f}" for w, z in sorted(words.items(), key=lambda kv: (-kv[1], kv[0]))]
        (DATA / name).write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"valid forms considered: {len(valid):,}  (blocked forms: {len(blocked_forms):,})")
    print(f"main:  {len(main_words):,}  (Zipf >= {a.main_zipf})")
    print(f"bonus: {len(bonus_words):,}  (Zipf {a.bonus_zipf}-{a.main_zipf}, "
          f"incl. {slang_kept} of {len(slang)} slang words)")


if __name__ == "__main__":
    main()
